/**
 * Standardized Error Codes
 * Consistent error codes for API responses
 */

export const ERROR_CODES = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ACCESS_DENIED: 'ACCESS_DENIED',
  
  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_VALUE: 'INVALID_VALUE',
  
  // Resource Errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',
  
  // Document Specific
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_ACCESS_DENIED: 'DOCUMENT_ACCESS_DENIED',
  INVALID_FILE_SIZE: 'INVALID_FILE_SIZE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  INVALID_STATUS: 'INVALID_STATUS',
  
  // System Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  TIMEOUT: 'TIMEOUT',
  
  // Rate Limiting
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

// Error code to HTTP status mapping
export const ERROR_CODE_TO_STATUS: Record<ErrorCode, number> = {
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.ACCESS_DENIED]: 403,
  
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.REQUIRED_FIELD]: 400,
  [ERROR_CODES.INVALID_FORMAT]: 400,
  [ERROR_CODES.INVALID_VALUE]: 400,
  
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.ALREADY_EXISTS]: 409,
  [ERROR_CODES.CONFLICT]: 409,
  
  [ERROR_CODES.DOCUMENT_NOT_FOUND]: 404,
  [ERROR_CODES.DOCUMENT_ACCESS_DENIED]: 403,
  [ERROR_CODES.INVALID_FILE_SIZE]: 400,
  [ERROR_CODES.INVALID_FILE_TYPE]: 400,
  [ERROR_CODES.INVALID_STATUS]: 400,
  
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.DATABASE_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.TIMEOUT]: 408,
  
  [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  [ERROR_CODES.QUOTA_EXCEEDED]: 429
};

// Helper function to get HTTP status from error code
export function getStatusFromErrorCode(code: ErrorCode): number {
  return ERROR_CODE_TO_STATUS[code] || 500;
}